In [1]:
import pandas as pd
from sklearn import preprocessing
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('OneDrive_2022-02-04/train.csv')

In [3]:
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:
X = df.drop(['Survived','Name','Ticket','Cabin','PassengerId'],1)
Y = df.Survived

In [6]:
X.head(10)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S
5       3    male   NaN      0      0   8.4583        Q
6       1    male  54.0      0      0  51.8625        S
7       3    male   2.0      3      1  21.0750        S
8       3  female  27.0      0      2  11.1333        S
9       2  female  14.0      1      0  30.0708        C

In [7]:
X.Age=X.Age.replace(to_replace=np.nan,value= X.Age.mean())
print(X.Sex.unique())
print(X.Embarked.unique())

['male' 'female']
['S' 'C' 'Q' nan]


In [8]:
X.head(10)

Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0       3    male  22.000000      1      0   7.2500        S
1       1  female  38.000000      1      0  71.2833        C
2       3  female  26.000000      0      0   7.9250        S
3       1  female  35.000000      1      0  53.1000        S
4       3    male  35.000000      0      0   8.0500        S
5       3    male  29.699118      0      0   8.4583        Q
6       1    male  54.000000      0      0  51.8625        S
7       3    male   2.000000      3      1  21.0750        S
8       3  female  27.000000      0      2  11.1333        S
9       2  female  14.000000      1      0  30.0708        C

In [9]:
X['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [10]:
X['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [11]:
X = pd.get_dummies(X, columns = ['Sex', 'Embarked'])

In [12]:
X

Pclass        Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
0         3  22.000000      1      0   7.2500           0         1   
1         1  38.000000      1      0  71.2833           1         0   
2         3  26.000000      0      0   7.9250           1         0   
3         1  35.000000      1      0  53.1000           1         0   
4         3  35.000000      0      0   8.0500           0         1   
..      ...        ...    ...    ...      ...         ...       ...   
886       2  27.000000      0      0  13.0000           0         1   
887       1  19.000000      0      0  30.0000           1         0   
888       3  29.699118      1      2  23.4500           1         0   
889       1  26.000000      0      0  30.0000           0         1   
890       3  32.000000      0      0   7.7500           0         1   

     Embarked_C  Embarked_Q  Embarked_S  
0             0           0           1  
1             1           0           0  
2             0           0           1  
3             0           0           1  
4             0           0           1  
..          ...         ...         ...  
886           0           0           1  
887           0           0           1  
888           0           0           1  
889           1           0           0  
890           0           1           0  

[891 rows x 10 columns]

In [13]:
Y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [14]:
min_max_scaler = preprocessing.MinMaxScaler() # feature scaling using min max scaler
x_scaled = min_max_scaler.fit_transform(X)
X = pd.DataFrame(x_scaled)
X_train, X_test_trainset,Y_train,Y_test_trainset= train_test_split(X, Y,test_size=0.30,random_state=1)

In [15]:
X_train1 = np.array(X_train)

In [16]:
X_train1.shape

(623, 10)

In [17]:
X_test_trainset = np.array(X_test_trainset)
Y_test_trainset = np.array(Y_test_trainset)

In [18]:
Y_train1 = np.array(Y_train).T

In [19]:
Y_train1

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,

In [120]:
def LogisticModel(X,Y,learning_rate,iteration):
    m,n = X.shape 
    theta = np.random.rand(n)
    for i in range(iterations):
        hypofunc = 1 / ( 1 + np.exp(-(np.dot(X,theta))))
        tmp = (hypofunc - Y.T)        
        #tmp = np.reshape( tmp, m )
        dtheta = (np.dot( X.T, tmp ))/m         
        theta = theta - learning_rate * dtheta
        learning_rate = learning_rate - 0.00001
        
    return theta
        
def predict(X,theta) :
        Z = 1 / ( 1 + np.exp( - (X.dot(theta)) ) )        
        Y = np.where( Z >= 0.5, 1, 0 )        
        return Y
def eval(X_test,theta,Y_test):
    Y_pred = predict( X_test,theta )    
    correctly_classified = 0
    for count in range( np.size( Y_pred ) ) :  
        
        if Y_test[count] == Y_pred[count] :            
            correctly_classified = correctly_classified + 1              
        count = count + 1
          
    print( "Accuracy on test set by our model       :  ", (correctly_classified / count) * 100 )

In [121]:
iterations = 1000
learning_rate = 0.01
theta = LogisticModel(X_train1, Y_train1, learning_rate = learning_rate, iteration = iterations)
theta

array([-0.02213963, -0.09449161,  0.0400181 ,  0.11193137,  0.77068685,
        0.66906065, -0.75552146,  0.29386339,  0.34175648, -0.40817674])

In [122]:
Y_pred = predict(X_test_trainset,theta)
Y_pred

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0])

In [124]:
eval(X_test_trainset,theta,Y_test_trainset)

Accuracy on test set by our model       :   75.74626865671642


In [125]:
#testing on the test set
df_test = pd.read_csv('OneDrive_2022-02-04/test.csv')

In [126]:
df_test.head(10)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
5          897       3                    Svensson, Mr. Johan Cervin    male   
6          898       3                          Connolly, Miss. Kate  female   
7          899       2                  Caldwell, Mr. Albert Francis    male   
8          900       3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
9          901       3                       Davies, Mr. John Samuel    male   

    Age  SibSp  Parch     Ticket     Fare Cabin Embarked  
0  34.5      0      0     330911   7.8292   NaN        Q  
1  47.0      1      0     363272   7.0000   NaN        S  
2  62.0      0      0     240276   9.6875   NaN        Q  
3  27.0      0      0     315154   8.6625   NaN        S  
4  22.0      1      1    3101298  12.2875   NaN        S  
5  14.0      0      0       7538   9.2250   NaN        S  
6  30.0      0      0     330972   7.6292   NaN        Q  
7  26.0      1      1     248738  29.0000   NaN        S  
8  18.0      0      0       2657   7.2292   NaN        C  
9  21.0      2      0  A/4 48871  24.1500   NaN        S

In [127]:
X_test = df_test.drop(['Name','Ticket','Cabin','PassengerId'],1)

In [128]:
Passengerid = df_test['PassengerId']
Passengerid
Passengerid_lst = np.array(Passengerid)
Passengerid_lst

array([ 892,  893,  894,  895,  896,  897,  898,  899,  900,  901,  902,
        903,  904,  905,  906,  907,  908,  909,  910,  911,  912,  913,
        914,  915,  916,  917,  918,  919,  920,  921,  922,  923,  924,
        925,  926,  927,  928,  929,  930,  931,  932,  933,  934,  935,
        936,  937,  938,  939,  940,  941,  942,  943,  944,  945,  946,
        947,  948,  949,  950,  951,  952,  953,  954,  955,  956,  957,
        958,  959,  960,  961,  962,  963,  964,  965,  966,  967,  968,
        969,  970,  971,  972,  973,  974,  975,  976,  977,  978,  979,
        980,  981,  982,  983,  984,  985,  986,  987,  988,  989,  990,
        991,  992,  993,  994,  995,  996,  997,  998,  999, 1000, 1001,
       1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012,
       1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023,
       1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034,
       1035, 1036, 1037, 1038, 1039, 1040, 1041, 10

In [129]:
X_test.Age=X_test.Age.replace(to_replace=np.nan,value= X_test.Age.mean())

In [130]:
X_test.head(20)

Pclass     Sex       Age  SibSp  Parch     Fare Embarked
0        3    male  34.50000      0      0   7.8292        Q
1        3  female  47.00000      1      0   7.0000        S
2        2    male  62.00000      0      0   9.6875        Q
3        3    male  27.00000      0      0   8.6625        S
4        3  female  22.00000      1      1  12.2875        S
5        3    male  14.00000      0      0   9.2250        S
6        3  female  30.00000      0      0   7.6292        Q
7        2    male  26.00000      1      1  29.0000        S
8        3  female  18.00000      0      0   7.2292        C
9        3    male  21.00000      2      0  24.1500        S
10       3    male  30.27259      0      0   7.8958        S
11       1    male  46.00000      0      0  26.0000        S
12       1  female  23.00000      1      0  82.2667        S
13       2    male  63.00000      1      0  26.0000        S
14       1  female  47.00000      1      0  61.1750        S
15       2  female  24.00000      1      0  27.7208        C
16       2    male  35.00000      0      0  12.3500        Q
17       3    male  21.00000      0      0   7.2250        C
18       3  female  27.00000      1      0   7.9250        S
19       3  female  45.00000      0      0   7.2250        C

In [131]:
X_test_list = ['Pclass','Age','SibSp','Parch','Fare','Sex_female','Sex_male','Embarked_C','Embarked_Q','Embarked_S']
X_test_list_categoric = ['Pclass','Sex','SibSp','Parch','Embarked']
X_test_list_numeric = ['Age','Fare']
for i in X_test_list:
    print(i,X_test.isnull().values.any())

Pclass True
Age True
SibSp True
Parch True
Fare True
Sex_female True
Sex_male True
Embarked_C True
Embarked_Q True
Embarked_S True


In [132]:
for i in X_test_list_categoric:
    X_test[i] = X_test[i].replace(to_replace = np.nan, value = X_test[i].value_counts().idxmax())

In [133]:
for i in X_test_list_numeric:
    X_test[i] = X_test[i].replace(to_replace=np.nan,value= X_test[i].mean())

In [134]:
X_test = pd.get_dummies(X_test, columns = ['Sex', 'Embarked'])

In [135]:
x_test_scaled = min_max_scaler.fit_transform(X_test)
X_test = pd.DataFrame(x_test_scaled)

In [136]:
X_test
X_test.info()
X_test.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       418 non-null    float64
 1   1       418 non-null    float64
 2   2       418 non-null    float64
 3   3       418 non-null    float64
 4   4       418 non-null    float64
 5   5       418 non-null    float64
 6   6       418 non-null    float64
 7   7       418 non-null    float64
 8   8       418 non-null    float64
 9   9       418 non-null    float64
dtypes: float64(10)
memory usage: 32.8 KB


(418, 10)

In [137]:
X_test1 = np.array(X_test)

In [138]:
X_test1

array([[1.        , 0.4527232 , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.61756561, 0.125     , ..., 0.        , 0.        ,
        1.        ],
       [0.5       , 0.8153765 , 0.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [1.        , 0.50547277, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [1.        , 0.39697468, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [1.        , 0.39697468, 0.125     , ..., 1.        , 0.        ,
        0.        ]])

In [139]:
Y_test_final = predict(X_test1,theta)

In [140]:
Y_test_final

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [141]:
submission_data = {'PassengerId': Passengerid_lst, 'Survived':Y_test_final}
df_final = pd.DataFrame(submission_data)

In [142]:
df_final

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [109]:
df_final.to_csv('submission1.csv', index = False)

Using SVM

In [166]:
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='rbf') # Gaussian Kernel

#Train the model using the training sets
clf.fit(X_train1, Y_train1)

In [168]:
from sklearn import metrics
y_pred1 = clf.predict(X_test_trainset)
print("Accuracy:",(metrics.accuracy_score(Y_test_trainset, y_pred1))*100)

Accuracy: 76.11940298507463


In [169]:
y_pred_svm_final = clf.predict(X_test1)

In [170]:
y_pred_svm_final

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [171]:
submission_data_svm = {'PassengerId': Passengerid_lst, 'Survived':y_pred_svm_final}

In [172]:
df_final_svm = pd.DataFrame(submission_data_svm)

In [173]:
df_final_svm

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [174]:
df_final_svm.to_csv('submission_svm.csv',index=False)