In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression as LogReg
import sklearn.preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
import seaborn as sb
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score as acc_score

from sklearn.neighbors import KNeighborsClassifier as KNN

In [2]:
#1
df = pd.read_csv('iris.csv')

In [3]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
df = df.drop('Id',axis = 1)

In [5]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
df['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [7]:
df.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [8]:
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])
df.head(100)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0             5.1           3.5            1.4           0.2        0
1             4.9           3.0            1.4           0.2        0
2             4.7           3.2            1.3           0.2        0
3             4.6           3.1            1.5           0.2        0
4             5.0           3.6            1.4           0.2        0
..            ...           ...            ...           ...      ...
95            5.7           3.0            4.2           1.2        1
96            5.7           2.9            4.2           1.3        1
97            6.2           2.9            4.3           1.3        1
98            5.1           2.5            3.0           1.1        1
99            5.7           2.8            4.1           1.3        1

[100 rows x 5 columns]

In [9]:
df_X = df.drop('Species',axis = 1)
df_Y = df['Species']

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(df_X, df_Y, test_size = 0.3,random_state = 0)

In [33]:
Y_train.shape

(105,)

In [34]:
model = LogReg()

In [35]:
model.fit(X_train,Y_train)

LogisticRegression()

In [36]:
y_pred = model.predict(X_test)

In [37]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [38]:
y_pred.shape

(45,)

In [39]:
cf_mat = confusion_matrix(Y_test, y_pred)
print('Confusion matrix is', cf_mat)

Confusion matrix is [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


In [40]:
accuracy = (cf_mat[0,0]+cf_mat[1,1]+cf_mat[2,2])/np.sum(cf_mat)

In [41]:
accuracy

0.9777777777777777

In [42]:
K = []
test_acc = []
  
for k in range(2, 21):
    model = KNN(n_neighbors = k)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test) 
    cf_mat = confusion_matrix(Y_test, y_pred)
    test_accuracy = np.trace(cf_mat)/np.sum(cf_mat)
    print('Accuracy of ',k,' neighbors model is ',test_accuracy)
    K.append(k)
    test_acc.append(test_accuracy)
    

Accuracy of  2  neighbors model is  0.9777777777777777
Accuracy of  3  neighbors model is  0.9777777777777777
Accuracy of  4  neighbors model is  0.9777777777777777
Accuracy of  5  neighbors model is  0.9777777777777777
Accuracy of  6  neighbors model is  0.9777777777777777
Accuracy of  7  neighbors model is  0.9777777777777777
Accuracy of  8  neighbors model is  0.9777777777777777
Accuracy of  9  neighbors model is  0.9777777777777777
Accuracy of  10  neighbors model is  0.9777777777777777
Accuracy of  11  neighbors model is  0.9777777777777777
Accuracy of  12  neighbors model is  0.9777777777777777
Accuracy of  13  neighbors model is  0.9777777777777777
Accuracy of  14  neighbors model is  0.9777777777777777
Accuracy of  15  neighbors model is  0.9777777777777777
Accuracy of  16  neighbors model is  0.9777777777777777
Accuracy of  17  neighbors model is  0.9777777777777777
Accuracy of  18  neighbors model is  0.9777777777777777
Accuracy of  19  neighbors model is  0.9777777777777777


In [19]:
#6
'''Since k is same for k between 2 to 20, we can take any k . Since its a benchmark dataset the accuracy is same for k that are used'''

'Since k is same for k between 2 to 20, we can take any k . Since its a benchmark dataset the accuracy is same for k that are used'

In [20]:
#7
'''Since iris dataset is a benchmark dataset, the performance for both the models used are similar'''

'Since iris dataset is a benchmark dataset, the performance for both the models used are similar'